version: '3.7'

services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - VERSION_ALPINE=${VERSION_ALPINE}
    container_name: nginx
    depends_on:
      - wordpress
    restart: on-failure
    networks:
       - inception_net
    ports:
      - 443:443
    volumes:
     - ${WP_VOLUME_SRCDIR}:${WP_VOLUME_DSTDIR}

  wordpress:
     image: wordpress
     build:
       context: ./requirements/wordpress
       args:
        - VERSION_ALPINE=${VERSION_ALPINE}
     container_name: wordpress
     depends_on:
      - mariadb
     restart: on-failure
     ports:
       - 9000:9000
     networks:
       - inception_net
     environment:
      WORDPRESS_DB_PASSWORD: "${DB_PASS}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_HOST: "${DB_HOST}"
     volumes:
      - ${WP_VOLUME_SRCDIR}:${WP_VOLUME_DSTDIR}
       
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - VERSION_ALPINE=${VERSION_ALPINE}
      dockerfile: ./Dockerfile
    image: mariadb
    restart: always
    networks:
      - inception_net
    expose:
      - "3306"
    volumes:
      - vol_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"

volumes:
    vol_wp:
      name: "${WP_VOLUME}"
      driver_opts:
        type: none
        o: bind
        device: ${WP_VOLUME_SRCDIR}
    vol_db:
      name: "${DB_VOLUME}"
      driver_opts:
        type: none
        o: bind
        device: ${DB_VOLUME_SRCDIR}

networks:
  inception_net:
    driver: bridge


