version: '3.7'

services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - VERSION_ALPINE=${VERSION_ALPINE}
    container_name: nginx
    depends_on:
      - wordpress
    restart: on-failure
    networks:
       - inception_net
    ports:
      - 443:443
    volumes:
     - ${VOL_NAME_WP}:${VOL_DIR_DST_WP}

  wordpress:
     image: wordpress
     build:
       context: ./requirements/wordpress
       args:
        - VERSION_ALPINE=${VERSION_ALPINE}
     container_name: wordpress
     depends_on:
      - mariadb
     restart: on-failure
     ports:
       - 9000:9000
     networks:
       - inception_net
     environment:
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_HOST: "${DB_HOST}"
     volumes:
      - ${VOL_NAME_WP}:${VOL_DIR_DST_WP}
       
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - VERSION_ALPINE=${VERSION_ALPINE}
      dockerfile: ./Dockerfile
    image: mariadb
    restart: always
    networks:
      - inception_net
    expose:
      - "3306"
    volumes:
      - vol_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

volumes:
    vol_wp:
      name: "${VOL_NAME_WP}"
      driver_opts:
        type: none
        o: bind
        device: ${VOL_DIR_SRC_WP}
    vol_db:
      name: "${VOL_NAME_DB}"
      driver_opts:
        type: none
        o: bind
        device: ${VOL_DIR_SRC_DB}

networks:
  inception_net:
    driver: bridge


